[pyprland]
plugins = ["scratchpads"]
[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "85% 70%"
max_size = "1920px 100%"
margin = 50
[scratchpads.email]
animation = "fromTop"
command = "uwsm app -- betterbird"
class = "eu.betterbird.Betterbird"
size = "80% 80%"
max_size = "1920px 100%"
margin = 40

[scratchpads.fdm]
animation = "fromTop"
command = "uwsm app -- fdm"
class = "fdm"
size = "80% 60%"
max_size = "1920px 100%"
margin = 40

[scratchpads.whatsapp]
animation = "fromTop"
command = "uwsm app -- whatsapp-linux-desktop"
class = "WhatsApp Desktop"
size = "80% 60%"
max_size = "1920px 100%"
margin = 40

[wallpapers]
path = "~/dotfiles/wallpapers_catppuccin"
interval = 60 # change every hour
extensions = ["jpg", "jpeg","png","gif"]
recurse = true
## Using swww
command = 'swww img --transition-type simple "[file]"'
clear_command = "swww clear"


